### ISSUE TITLE
No section 'testenv' in 4.3.0

### ISSUE THREAD

**Issue by andrewmichaelsmith** [Simplistix/testfixtures#21] opened 2015-09-15 16:44 UTC
We're using python2.7 and we install testfixtures by defining it in our setuptools setup.py tests_require.

When we do a "python setup.py install" or an easy_install. Since 4.3.0 was released we get the error below when running tests on our application.

Downgrading to 4.2.0 fixed this issue.

```
Processing testfixtures-4.3.0.tar.gz
Writing /tmp/easy_install-3YvN2G/testfixtures-4.3.0/setup.cfg
Running testfixtures-4.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3YvN2G/testfixtures-4.3.0/egg-dist-tmp-_0xl94
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
..
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/nose/commands.py", line 147, in run
    self.distribution.tests_require)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 836, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1081, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1093, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 380, in fetch_build_egg
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 629, in easy_install
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 659, in install_item
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 842, in install_eggs
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1070, in build_and_install
    
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1056, in run_setup
    
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 240, in run_setup
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 193, in setup_context
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 164, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 139, in resume
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 152, in save_modules
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 193, in setup_context
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 237, in run_setup
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 267, in run
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 236, in runner
  File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-3YvN2G/testfixtures-4.3.0/setup.py", line 20, in <module>
    'testfixtures>=4.0.2',
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'testenv'
```

**Comment by cjw296** [comment] 2015-09-15 16:53
Dupe of #20, please use 4.3.3 instead.

**Closed by cjw296** 2015-09-15 16:53 UTC

**Comment by andrewmichaelsmith** [comment] 2015-09-15 20:01
Aha, thanks!
