### ISSUE TITLE
compare() accepts (and ignores) arbitrary kwargs; bad for usability

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#96] opened 2018-11-28 20:07 UTC
Consider the following examples:
```
>>> compare(0, 1, prefix='before')
AssertionError: before: 0 != 1
>>> compare(0, 1, suffix='after')
AssertionError: 0 != 1
after
>>> compare(0, 1, postfix='ignored!')
AssertionError: 0 != 1
```

The `postfix` kwarg is not supported so is quietly ignored. This is bad for usability because a typo in a kwarg name will be silently ignored.

If you want to get anal about versioning (which you probably don't, but let's go there anyway, since you're using semver) this also implies that adding support for any new kwarg is technically a breaking change (since it modifies the current behaviour associated with that kwarg!)

**Comment by cjw296** [comment] 2018-11-28 21:51
This is a really thorny one and I'd love suggestions.
The problem is that any comparer registered can take parameters, so it's not easy to prevent 'wrong' keywords up front.
I do wonder if the context could keep track of what keywords had been used and have some kind of try/finally that barfs if no other error has been raised and there are unused keywords?

**Comment by asqui** [comment] 2018-12-02 14:15
Ah, if the idea of the flexible kwargs is to provide flexible configuration for custom comparers then yes, I'd go for an instrumented dictionary that keeps track of what kwargs have been looked at, and fails if any have been "unused".

In terms of design, it would probably be better if comparers specified explicitly what arguments they expect. That way you could do the check up-front, not be exposed to the possibility of comparers only inspecting certain arguments conditionally, potentially warn about arg clashes between comparers, etc. but maybe it's too late for such a design change?

**Comment by asqui** [comment] 2018-12-02 14:38
How likely is it that a comparer would have conditional argument inspection? This would be a breaking change for such comparers...

**Comment by cjw296** [comment] 2018-12-02 14:40
[This](https://github.com/Simplistix/testfixtures/blob/master/testfixtures/comparison.py#L427) is the only way to get an option, so not sure what conditional argument inspection would look like?

**Comment by asqui** [comment] 2018-12-02 14:46
It might look like this:
```
if ctx.get_option('a', default=False):
    ctx.get_option('b')
```

Or this:
```
if not exact_match(...):
    ctx.get_option('some_option')
```

**Comment by cjw296** [comment] 2018-12-02 14:47
Oh, right, I think it'd be fine to break those usages. It's easy enough to fix for anyone who has those but I'm not aware of any.

**Comment by cjw296** [comment] 2018-12-13 19:04
Now I remember, I did try this before. Here's my current PR and illustration of the problem: 
https://github.com/Simplistix/testfixtures/pull/100
...with these test failures:
https://travis-ci.org/Simplistix/testfixtures/jobs/467659424

The problem is that we short-circuit on equality. That means you can specify a legitimate option, but it'll never get used, and that's okay.

Open to other suggestions, but closing this for the time being.

**Closed by cjw296** 2018-12-13 19:04 UTC

**Comment by asqui** [comment] 2018-12-16 16:40
Ah okay, that's an even more severe case of "conditional argument inspection" then :-)

I guess the only way to get around this would be "if comparers specified explicitly what arguments they expect" but that's a more severe breaking change to the comparer interface, so you probably don't want that at this point.

**Comment by cjw296** [comment] 2018-12-17 15:41
Also not sure how practical that is, we'd have to check *all* arguments of *all* comparers on each compare call, and they'd have to define those up front... I suspect what's there is the most pragmatic thing...
