### ISSUE TITLE
check_present shows nothing and throws AssertionError when checking a particular while check returns all logs

### ISSUE THREAD

**Issue by 0xLuz** [simplistix/testfixtures#176] opened 2022-06-24 18:31 UTC
I need to check one single log and for that, I tried to use `check_present()` and it throws an error like no log was generated.

![Screen Shot 2022-06-24 at 15 23 00](https://user-images.githubusercontent.com/829669/175642525-78f27965-8076-4b9c-a36c-4eeec42ea3d8.png)

However when I use `check` I see the log was generated but I get an AssertionError because I didn't specify the other logs. 

![Screen Shot 2022-06-24 at 15 30 11](https://user-images.githubusercontent.com/829669/175644294-3cbcef7c-9714-470d-b771-78a4b08f4399.png)

I only want to check that last log. Is there any config I'm doing wrong to make that happen?

**Comment by cjw296** [comment] 2022-06-29 23:37
Please don't post images of text, they're very hard to work with. Just use markdown's code formatting.

You haven't provided enough information for me to comment sensibly.

Please can you post all the code of a small reproducer that shows the problem you're experiencing?

**Comment by JoabMendes** [comment] 2022-06-30 15:39
I'm closing this issue since the problem was that I didn't configure the django logging properly. it's working now.

**Closed as completed by JoabMendes** 2022-06-30 15:39 UTC
