### ISSUE TITLE
Comparing mock._Call objects using equals operator causes RecursionError after import testfixtures

### ISSUE THREAD

**Issue by pjxiao** [Simplistix/testfixtures#102] opened 2018-12-28 08:37 UTC
The following code works fine with testfixtures 6.3.0 or Python 3.6.7.
But when I use testfixtures 6.4.1 and Python 3.6.8, the same code fails:
```console
$ pip install testfixtures
Collecting testfixtures
  Using cached https://files.pythonhosted.org/packages/d7/c6/ef5514a3e36b2cddc61a712952027e3333ee32fb5fa079b1e5f3ea1bbf5b/testfixtures-6.4.1-py2.py3-none-any.whl
Installing collected packages: testfixtures
Successfully installed testfixtures-6.4.1
```
```python
$ python
Python 3.6.8 (default, Dec 26 2018, 08:57:24)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import testfixtures
>>> from unittest.mock import call
>>> a = call({'key': 'value'})
>>> b = call({'key': 'value'})
>>> assert a == b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/testfixtures/mock.py", line 39, in __eq__
    and self.parent != other.parent):
  File "/usr/local/lib/python3.6/site-packages/testfixtures/mock.py", line 39, in __eq__
    and self.parent != other.parent):
  File "/usr/local/lib/python3.6/site-packages/testfixtures/mock.py", line 39, in __eq__
    and self.parent != other.parent):
  [Previous line repeated 195 more times]
  File "/usr/local/lib/python3.6/site-packages/testfixtures/mock.py", line 38, in __eq__
    if (getattr(self, 'parent', None) and getattr(other, 'parent', None)
  File "/usr/local/lib/python3.6/unittest/mock.py", line 2081, in __getattr__
    return _Call(name=name, parent=self, from_kall=False)
RecursionError: maximum recursion depth exceeded
```

**Comment by dsalisbury** [comment] 2019-01-02 03:01
It looks like this commit is the cause:

https://github.com/python/cpython/commit/70ca3fce9fe2bdd7bf97d5fe1299cfa5e32b3ad4

**Comment by cjw296** [comment] 2019-01-04 07:59
@dsalisbury / @pjxiao - I think this is fixed by 5f9d56d798adef223486ef022560e1aab325e291. Please can you confirm and I'll cut a release.

**Comment by dsalisbury** [comment] 2019-01-07 03:49
Sorry for the slow reply. I didn't get any time over the weekend to check this.

Seems to be broken still for me:

To recreate:

```
$ docker run --rm -it python:3.7.2-alpine /bin/sh

/ # apk add git
/ # git clone https://github.com/Simplistix/testfixtures.git
/ # cd testfixtures/
/testfixtures # pip install -e .[test]
/testfixtures # pytest -k "test_mock"
...
===================================================== FAILURES =====================================================
_____________________________________ TestCall.test_non_root_params_not_equal ______________________________________

self = <testfixtures.tests.test_mock.TestCall object at 0x7f1750a875f8>

    def test_non_root_params_not_equal(self):
        self.check_raises(
            call.foo(x=1).bar(),
            call.foo(x=2).bar(),
>           '\n'
            "'call.foo(x=1)'\n"
            '!=\n'
            "'call.foo(x=2)'"
        )

testfixtures/tests/test_mock.py:31:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
testfixtures/tests/test_compare.py:47: in check_raises
    compare(*args, **kw)
testfixtures/comparison.py:488: in different
    result = comparer(x, y, self)
testfixtures/comparison.py:321: in compare_call
    return compare_call(x.parent, y.parent, context)
testfixtures/comparison.py:321: in compare_call
    return compare_call(x.parent, y.parent, context)
...
snipped
...
E               RecursionError: maximum recursion depth exceeded

/usr/local/lib/python3.7/unittest/mock.py:2038: RecursionError
============================== 1 failed, 14 passed, 1061 deselected in 14.75 seconds ===============================
```

In `compare_call` of `mock.py` it's still looking at the `parent` attribute rather than `_mock_parent`:

```
    if x_name == y_name and x_args == y_args and x_kw == y_kw:
        return compare_call(x.parent, y.parent, context)
```

I don't get why it's passing in Travis though :|

**Comment by cjw296** [comment] 2019-01-07 06:55
Travis doesn't use the latest Python versions, and this change was only made in 3.6.8 and 3.7.2.
Let me see if I can fix this...

**Comment by cjw296** [comment] 2019-01-07 06:59
Okay, can you give add392c a spin?

**Comment by dsalisbury** [comment] 2019-01-07 22:02
> Okay, can you give [add392c](https://github.com/Simplistix/testfixtures/commit/add392caa8e812898adc8bacd8fbcc3cfabcc0a1) a spin?

Looks good 👍

**Comment by pjxiao** [comment] 2019-01-08 01:18
I'm sorry to be late for replying. In my environment, 5f9d56d works fine!

## Log

### prepare

```console
$ docker run --rm -it python:3.6 /bin/bash -li
root@d2a129ddc718:/# cd `mktemp -d`
```

### current version

```console
root@d2a129ddc718:/tmp/tmp.hXijaHV8CO# python -m venv .venv-before
root@d2a129ddc718:/tmp/tmp.hXijaHV8CO# .venv-before/bin/pip install testfixtures
Collecting testfixtures
  Downloading https://files.pythonhosted.org/packages/d7/c6/ef5514a3e36b2cddc61a712952027e3333ee32fb5fa079b1e5f3ea1bbf5b/testfixtures-6.4.1-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 3.7MB/s
Installing collected packages: testfixtures
Successfully installed testfixtures-6.4.1
root@d2a129ddc718:/tmp/tmp.hXijaHV8CO# .venv-before/bin/python
Python 3.6.8 (default, Dec 29 2018, 07:23:17)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest.mock import call
>>> a = call({'key': 'value'})
>>> b = call({'key': 'value'})
>>> assert a == b
>>> import testfixtures
>>> assert a == b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.hXijaHV8CO/.venv-before/lib/python3.6/site-packages/testfixtures/mock.py", line 39, in __eq__
    and self.parent != other.parent):
  File "/tmp/tmp.hXijaHV8CO/.venv-before/lib/python3.6/site-packages/testfixtures/mock.py", line 39, in __eq__
    and self.parent != other.parent):
  File "/tmp/tmp.hXijaHV8CO/.venv-before/lib/python3.6/site-packages/testfixtures/mock.py", line 39, in __eq__
    and self.parent != other.parent):
  [Previous line repeated 195 more times]
  File "/tmp/tmp.hXijaHV8CO/.venv-before/lib/python3.6/site-packages/testfixtures/mock.py", line 38, in __eq__
    if (getattr(self, 'parent', None) and getattr(other, 'parent', None)
  File "/usr/local/lib/python3.6/unittest/mock.py", line 2081, in __getattr__
    return _Call(name=name, parent=self, from_kall=False)
RecursionError: maximum recursion depth exceeded
>>>
```

### 5f9d56d

```console
root@d2a129ddc718:/tmp/tmp.hXijaHV8CO# python -m venv .venv-after
root@d2a129ddc718:/tmp/tmp.hXijaHV8CO# .venv-after/bin/pip install git+https://github.com/Simplistix/testfixtures.git@5f9d56d798adef223486ef022560e1aab325e291
Collecting git+https://github.com/Simplistix/testfixtures.git@5f9d56d798adef223486ef022560e1aab325e291
  Cloning https://github.com/Simplistix/testfixtures.git (to revision 5f9d56d798adef223486ef022560e1aab325e291) to /tmp/pip-req-build-qnsi4a13
Installing collected packages: testfixtures
  Running setup.py install for testfixtures ... done
Successfully installed testfixtures-6.4.1
root@d2a129ddc718:/tmp/tmp.hXijaHV8CO# .venv-after/bin/python
Python 3.6.8 (default, Dec 29 2018, 07:23:17)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from unittest.mock import call
>>> a = call({'key': 'value'})
>>> b = call({'key': 'value'})
>>> assert a == b
>>> import testfixtures
>>> assert a == b
>>>
```

**Comment by cjw296** [comment] 2019-01-09 08:21
Great, the 6.4.2 release will be up on pypi shortly.

**Closed by cjw296** 2019-01-09 08:21 UTC
